version: '3'

services:
  activemq-service:
    image: webcenter/activemq
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=test
      - ACTIVEMQ_ADMIN_PASSWORD=test
    ports:
      - '8161:8161'
      - '5672:5672'
  postgres:
    image: postgres:13.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - postgres:/var/lib/postgresql/data
  sqs:
    image: vsouza/sqs-local
    ports:
      - '9324:9324'
volumes:
  postgres:
